name: codebase_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 4.0.6
repository: https://github.com/moyra-co/flutter_translate

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: